upstream auth_upstream    { server auth-service:3001; }
upstream workout_upstream { server workout-service:3002; }
upstream stats_upstream   { server stats-service:3003; }
upstream frontend_upstream { server frontend:5173; }

server {
    listen 80;
    server_name localhost;
    client_max_body_size 10M;

    location /auth {
        proxy_pass http://auth_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /profiles {
        proxy_pass http://auth_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /workouts {
        proxy_pass http://workout_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /stats {
        proxy_pass http://stats_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
